name: adaptive_components
description: Implements Material Adaptive Components.
version: 0.0.2
homepage: https://github.com/material-components/material-components-flutter-adaptive

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  adaptive_breakpoints: ^0.0.4
  adaptive_navigation: ^0.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.4
