name: adaptive_breakpoints
description: A Flutter package for adaptive breakpoints following the Material guidelines.
version: 0.1.1
homepage: https://github.com/material-components/material-components-flutter-adaptive

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter
